---
- name: set backup_path fact
  set_fact:
    backup_path: "{{ playbook_dir }}/backup"

- name: create backup paths
  file:
    path: "{{ backup_path }}"
    state: directory
  run_once: yes
  delegate_to: localhost

- name: debug
  debug: msg="{{playbook_dir}}/{{ ansible_network_os }}.yml"

- name: include device specific tasks
  include_tasks: "{{ ansible_network_os }}.yml"

