---

- name: include objects variables
  include_vars:
    file: "group_vars/objects.yml"

- name: create fortios addrgrp in vdom
  fortios_config:
    host: "{{inventory_hostname}}"
    src: "templates/fortios_objects.j2"
    vdom: "{{vdom}}"
  when: vdom is defined

- name: create fortios addrgrp in global
  fortios_config:
    host: "{{inventory_hostname}}"
    src: "templates/fortios_objects.j2"
  when: vdom is not defined
